# This file should contain all the record creation needed to seed
# the database with its default values.
# The data can then be loaded with the rake db:seed
# (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# user = CreateAdminService.new.call
# puts 'CREATED ADMIN USER: ' << user.email

[:keppler_admin, :client].each do |name|
  Role.create name: name
  puts "#{name} has been created"
end

User.create(
  name: 'Admin', email: 'admin@keppler.com', password: '12345678',
  password_confirmation: '12345678', role_ids: '1'
)
#type_project 
TypeProject.create(name:'TODOS')
TypeProject.create(name:'METELMECÁNICA')
TypeProject.create(name:'CIVIL')
TypeProject.create(name:'ELECTRICIDAD')

StackState.create(name:'Amazonas')
StackState.create(name:'Anzoátegui')
StackState.create(name:'Apure')
StackState.create(name:'Aragua')
StackState.create(name:'Barinas')
StackState.create(name:'Bolívar')
StackState.create(name:'Carabobo')
StackState.create(name:'Cojedes')
StackState.create(name:'Delta Amacuro')
StackState.create(name:'Distrito Capital')
StackState.create(name:'Falcón')
StackState.create(name:'Guárico')
StackState.create(name:'Lara')
StackState.create(name:'Mérida')
StackState.create(name:'Miranda')
StackState.create(name:'Monagas')
StackState.create(name:'Nueva Esparta')
StackState.create(name:'Portuguesa')
StackState.create(name:'Sucre')
StackState.create(name:'Táchira')
StackState.create(name:'Trujillo')
StackState.create(name:'Vargas')
StackState.create(name:'Yaracuy')
StackState.create(name:'Zulia')

#ciudades
#amazonas
StackCity.create(name:'Maroa',stack_state_id:'1')
StackCity.create(name:'Puerto Ayacucho',stack_state_id:'1')
StackCity.create(name:'San Fernando de Atabapo',stack_state_id:'1')

#anzoategui
StackCity.create(name:'Anaco',stack_state_id:'2')
StackCity.create(name:'Aragua de Barcelona',stack_state_id:'2')
StackCity.create(name:'Barcelona',stack_state_id:'2')
StackCity.create(name:'Boca de Uchire',stack_state_id:'2')
StackCity.create(name:'Cantaura',stack_state_id:'2')
StackCity.create(name:'Clarines',stack_state_id:'2')
StackCity.create(name:'El Chaparro',stack_state_id:'2')
StackCity.create(name:'El Pao Anzoátegui',stack_state_id:'2')
StackCity.create(name:'El Tigre',stack_state_id:'2')
StackCity.create(name:'El Tigrito',stack_state_id:'2')
StackCity.create(name:'Guanape',stack_state_id:'2')
StackCity.create(name:'Guanta',stack_state_id:'2')
StackCity.create(name:'Lechería',stack_state_id:'2')
StackCity.create(name:'Onoto',stack_state_id:'2')
StackCity.create(name:'Pariaguán',stack_state_id:'2')
StackCity.create(name:'Píritu',stack_state_id:'2')
StackCity.create(name:'Puerto La Cruz',stack_state_id:'2')
StackCity.create(name:'Puerto Píritu',stack_state_id:'2')
StackCity.create(name:'Sabana de Uchire',stack_state_id:'2')
StackCity.create(name:'San Mateo Anzoátegui',stack_state_id:'2')
StackCity.create(name:'San Pablo Anzoátegui',stack_state_id:'2')
StackCity.create(name:'San Tomé',stack_state_id:'2')
StackCity.create(name:'Santa Ana de Anzoátegui',stack_state_id:'2')
StackCity.create(name:'Santa Fe Anzoátegui',stack_state_id:'2')
StackCity.create(name:'Santa Rosa',stack_state_id:'2')
StackCity.create(name:'Soledad',stack_state_id:'2')
StackCity.create(name:'Urica',stack_state_id:'2')
StackCity.create(name:'Valle de Guanape',stack_state_id:'2')

#Apure
StackCity.create(name:'Achaguas',stack_state_id:'3')
StackCity.create(name:'Biruaca',stack_state_id:'3')
StackCity.create(name:'Bruzual',stack_state_id:'3')
StackCity.create(name:'El Amparo',stack_state_id:'3')
StackCity.create(name:'El Nula',stack_state_id:'3')
StackCity.create(name:'Elorza',stack_state_id:'3')
StackCity.create(name:'Guasdualito',stack_state_id:'3')
StackCity.create(name:'Mantecal',stack_state_id:'3')
StackCity.create(name:'Puerto Páez',stack_state_id:'3')
StackCity.create(name:'San Fernando de Apure',stack_state_id:'3')
StackCity.create(name:'San Juan de Payara',stack_state_id:'3')

#Aragua
StackCity.create(name:'Barbacoas',stack_state_id:'4')
StackCity.create(name:'Cagua',stack_state_id:'4')
StackCity.create(name:'Camatagua',stack_state_id:'4')
StackCity.create(name:'Choroní',stack_state_id:'4')
StackCity.create(name:'Colonia Tovar',stack_state_id:'4')
StackCity.create(name:'El Consejo',stack_state_id:'4')
StackCity.create(name:'La Victoria',stack_state_id:'4')
StackCity.create(name:'Las Tejerías',stack_state_id:'4')
StackCity.create(name:'Magdaleno',stack_state_id:'4')
StackCity.create(name:'Maracay',stack_state_id:'4')
StackCity.create(name:'Ocumare de La Costa',stack_state_id:'4')
StackCity.create(name:'Palo Negro',stack_state_id:'4')
StackCity.create(name:'San Casimiro',stack_state_id:'4')
StackCity.create(name:'San Mateo',stack_state_id:'4')
StackCity.create(name:'San Sebastián',stack_state_id:'4')
StackCity.create(name:'Santa Cruz de Aragua',stack_state_id:'4')
StackCity.create(name:'Tocorón',stack_state_id:'4')
StackCity.create(name:'Turmero',stack_state_id:'4')
StackCity.create(name:'Villa de Cura',stack_state_id:'4')
StackCity.create(name:'Zuata',stack_state_id:'4')

#barinas
StackCity.create(name:'Barinas',stack_state_id:'5')
StackCity.create(name:'Barinitas',stack_state_id:'5')
StackCity.create(name:'Barrancas',stack_state_id:'5')
StackCity.create(name:'Calderas',stack_state_id:'5')
StackCity.create(name:'Capitanejo',stack_state_id:'5')
StackCity.create(name:'Ciudad Bolivia',stack_state_id:'5')
StackCity.create(name:'El Cantón',stack_state_id:'5')
StackCity.create(name:'Las Veguitas',stack_state_id:'5')
StackCity.create(name:'Libertad de Barinas',stack_state_id:'5')
StackCity.create(name:'Sabaneta',stack_state_id:'5')
StackCity.create(name:'Santa Bárbara de Barinas',stack_state_id:'5')
StackCity.create(name:'Socopó',stack_state_id:'5')

#bolivar
StackCity.create(name:'Caicara del Orinoco',stack_state_id:'6')
StackCity.create(name:'Canaima',stack_state_id:'6')
StackCity.create(name:'Ciudad Bolívar',stack_state_id:'6')
StackCity.create(name:'Ciudad Piar',stack_state_id:'6')
StackCity.create(name:'El Callao',stack_state_id:'6')
StackCity.create(name:'El Dorado',stack_state_id:'6')
StackCity.create(name:'El Manteco',stack_state_id:'6')
StackCity.create(name:'El Palmar',stack_state_id:'6')
StackCity.create(name:'El Pao',stack_state_id:'6')
StackCity.create(name:'Guasipati',stack_state_id:'6')
StackCity.create(name:'Guri',stack_state_id:'6')
StackCity.create(name:'La Paragua',stack_state_id:'6')
StackCity.create(name:'Matanzas',stack_state_id:'6')
StackCity.create(name:'Puerto Ordaz',stack_state_id:'6')
StackCity.create(name:'San Félix',stack_state_id:'6')
StackCity.create(name:'Santa Elena de Uairén',stack_state_id:'6')
StackCity.create(name:'Tumeremo',stack_state_id:'6')
StackCity.create(name:'Unare',stack_state_id:'6')
StackCity.create(name:'Upata',stack_state_id:'6')

#Carabobo
StackCity.create(name:'Bejuma',stack_state_id:'7')
StackCity.create(name:'Belén',stack_state_id:'7')
StackCity.create(name:'Campo de Carabobo',stack_state_id:'7')
StackCity.create(name:'Canoabo',stack_state_id:'7')
StackCity.create(name:'Central Tacarigua',stack_state_id:'7')
StackCity.create(name:'Chirgua',stack_state_id:'7')
StackCity.create(name:'Ciudad Alianza',stack_state_id:'7')
StackCity.create(name:'El Palito',stack_state_id:'7')
StackCity.create(name:'Guacara',stack_state_id:'7')
StackCity.create(name:'Guigue',stack_state_id:'7')
StackCity.create(name:'Las Trincheras',stack_state_id:'7')
StackCity.create(name:'Los Guayos',stack_state_id:'7')
StackCity.create(name:'Mariara',stack_state_id:'7')
StackCity.create(name:'Miranda',stack_state_id:'7')
StackCity.create(name:'Montalbán',stack_state_id:'7')
StackCity.create(name:'Morón',stack_state_id:'7')
StackCity.create(name:'Naguanagua',stack_state_id:'7')
StackCity.create(name:'Puerto Cabello',stack_state_id:'7')
StackCity.create(name:'San Joaquín',stack_state_id:'7')
StackCity.create(name:'Tocuyito',stack_state_id:'7')
StackCity.create(name:'Urama',stack_state_id:'7')
StackCity.create(name:'Valencia',stack_state_id:'7')
StackCity.create(name:'Vigirimita',stack_state_id:'7')

#cojedes
StackCity.create(name:'Aguirre',stack_state_id:'8')
StackCity.create(name:'Apartaderos Cojedes',stack_state_id:'8')
StackCity.create(name:'Arismendi',stack_state_id:'8')
StackCity.create(name:'Camuriquito',stack_state_id:'8')
StackCity.create(name:'El Baúl',stack_state_id:'8')
StackCity.create(name:'El Limón',stack_state_id:'8')
StackCity.create(name:'El Pao Cojedes',stack_state_id:'8')
StackCity.create(name:'El Socorro',stack_state_id:'8')
StackCity.create(name:'La Aguadita',stack_state_id:'8')
StackCity.create(name:'Las Vegas',stack_state_id:'8')
StackCity.create(name:'Libertad de Cojedes',stack_state_id:'8')
StackCity.create(name:'Mapuey',stack_state_id:'8')
StackCity.create(name:'Piñedo',stack_state_id:'8')
StackCity.create(name:'Samancito',stack_state_id:'8')
StackCity.create(name:'San Carlos',stack_state_id:'8')
StackCity.create(name:'Sucre',stack_state_id:'8')
StackCity.create(name:'Tinaco',stack_state_id:'8')
StackCity.create(name:'Tinaquillo',stack_state_id:'8')
StackCity.create(name:'Vallecito',stack_state_id:'8')

#delta amacuro
StackCity.create(name:'Tucupita',stack_state_id:'9')

#distrito capital
StackCity.create(name:'Caracas',stack_state_id:'10')

#falcon
StackCity.create(name:'Adícora',stack_state_id:'11')
StackCity.create(name:'Boca de Aroa',stack_state_id:'11')
StackCity.create(name:'Cabure',stack_state_id:'11')
StackCity.create(name:'Capadare',stack_state_id:'11')
StackCity.create(name:'Capatárida',stack_state_id:'11')
StackCity.create(name:'Chichiriviche',stack_state_id:'11')
StackCity.create(name:'Churuguara',stack_state_id:'11')
StackCity.create(name:'Coro',stack_state_id:'11')
StackCity.create(name:'Cumarebo',stack_state_id:'11')
StackCity.create(name:'Dabajuro',stack_state_id:'11')
StackCity.create(name:'Judibana',stack_state_id:'11')
StackCity.create(name:'La Cruz de Taratara',stack_state_id:'11')
StackCity.create(name:'La Vela de Coro',stack_state_id:'11')
StackCity.create(name:'Los Taques',stack_state_id:'11')
StackCity.create(name:'Maparari',stack_state_id:'11')
StackCity.create(name:'Mene de Mauroa',stack_state_id:'11')
StackCity.create(name:'Mirimire',stack_state_id:'11')
StackCity.create(name:'Pedregal',stack_state_id:'11')
StackCity.create(name:'Píritu',stack_state_id:'11')
StackCity.create(name:'Pueblo Nuevo',stack_state_id:'11')
StackCity.create(name:'Puerto Cumarebo',stack_state_id:'11')
StackCity.create(name:'Punta Cardón',stack_state_id:'11')
StackCity.create(name:'Punto Fijo',stack_state_id:'11')
StackCity.create(name:'San Juan de Los Cayos',stack_state_id:'11')
StackCity.create(name:'San Luis',stack_state_id:'11')
StackCity.create(name:'Santa Ana Falcón',stack_state_id:'11')
StackCity.create(name:'Santa Cruz De Bucaral',stack_state_id:'11')
StackCity.create(name:'Tocopero',stack_state_id:'11')
StackCity.create(name:'Tocuyo de La Costa',stack_state_id:'11')
StackCity.create(name:'Tucacas',stack_state_id:'11')
StackCity.create(name:'Yaracal',stack_state_id:'11')

#guarico

StackCity.create(name:'Altagracia de Orituco',stack_state_id:'12')
StackCity.create(name:'Cabruta',stack_state_id:'12')
StackCity.create(name:'Calabozo',stack_state_id:'12')
StackCity.create(name:'Camaguán',stack_state_id:'12')
StackCity.create(name:'Chaguaramas Guárico',stack_state_id:'12')
StackCity.create(name:'El Socorro',stack_state_id:'12')
StackCity.create(name:'El Sombrero',stack_state_id:'12')
StackCity.create(name:'Las Mercedes de Los Llanos',stack_state_id:'12')
StackCity.create(name:'Lezama',stack_state_id:'12')
StackCity.create(name:'Onoto',stack_state_id:'12')
StackCity.create(name:'Ortíz',stack_state_id:'12')
StackCity.create(name:'San José de Guaribe',stack_state_id:'12')
StackCity.create(name:'San Juan de Los Morros',stack_state_id:'12')
StackCity.create(name:'San Rafael de Laya',stack_state_id:'12')
StackCity.create(name:'Santa María de Ipire',stack_state_id:'12')
StackCity.create(name:'Tucupido',stack_state_id:'12')
StackCity.create(name:'Valle de La Pascua',stack_state_id:'12')
StackCity.create(name:'Zaraza',stack_state_id:'12')

#lara

StackCity.create(name:'Aguada Grande',stack_state_id:'13')
StackCity.create(name:'Atarigua',stack_state_id:'13')
StackCity.create(name:'Barquisimeto',stack_state_id:'13')
StackCity.create(name:'Bobare',stack_state_id:'13')
StackCity.create(name:'Cabudare',stack_state_id:'13')
StackCity.create(name:'Carora',stack_state_id:'13')
StackCity.create(name:'Cubiro',stack_state_id:'13')
StackCity.create(name:'Cují',stack_state_id:'13')
StackCity.create(name:'Duaca',stack_state_id:'13')
StackCity.create(name:'El Manzano',stack_state_id:'13')
StackCity.create(name:'El Tocuyo',stack_state_id:'13')
StackCity.create(name:'Guaríco',stack_state_id:'13')
StackCity.create(name:'Humocaro Alto',stack_state_id:'13')
StackCity.create(name:'Humocaro Bajo',stack_state_id:'13')
StackCity.create(name:'La Miel',stack_state_id:'13')
StackCity.create(name:'Moroturo',stack_state_id:'13')
StackCity.create(name:'Quíbor',stack_state_id:'13')
StackCity.create(name:'Río Claro',stack_state_id:'13')
StackCity.create(name:'Sanare',stack_state_id:'13')
StackCity.create(name:'Santa Inés',stack_state_id:'13')
StackCity.create(name:'Sarare',stack_state_id:'13')
StackCity.create(name:'Siquisique',stack_state_id:'13')
StackCity.create(name:'Tintorero',stack_state_id:'13')

#merida

StackCity.create(name:'Apartaderos Mérida',stack_state_id:'14')
StackCity.create(name:'Arapuey',stack_state_id:'14')
StackCity.create(name:'Bailadores',stack_state_id:'14')
StackCity.create(name:'Caja Seca',stack_state_id:'14')
StackCity.create(name:'Canaguá',stack_state_id:'14')
StackCity.create(name:'Chachopo',stack_state_id:'14')
StackCity.create(name:'Chiguara',stack_state_id:'14')
StackCity.create(name:'Ejido',stack_state_id:'14')
StackCity.create(name:'El Vigía',stack_state_id:'14')
StackCity.create(name:'La Azulita',stack_state_id:'14')
StackCity.create(name:'La Playa',stack_state_id:'14')
StackCity.create(name:'Lagunillas Mérida',stack_state_id:'14')
StackCity.create(name:'Mérida',stack_state_id:'14')
StackCity.create(name:'Mesa de Bolívar',stack_state_id:'14')
StackCity.create(name:'Mucuchíes',stack_state_id:'14')
StackCity.create(name:'Mucujepe',stack_state_id:'14')
StackCity.create(name:'Mucuruba',stack_state_id:'14')
StackCity.create(name:'Nueva Bolivia',stack_state_id:'14')
StackCity.create(name:'Palmarito',stack_state_id:'14')
StackCity.create(name:'Pueblo Llano',stack_state_id:'14')
StackCity.create(name:'Santa Cruz de Mora',stack_state_id:'14')
StackCity.create(name:'Santa Elena de Arenales',stack_state_id:'14')
StackCity.create(name:'Santo Domingo',stack_state_id:'14')
StackCity.create(name:'Tabáy',stack_state_id:'14')
StackCity.create(name:'Timotes',stack_state_id:'14')
StackCity.create(name:'Torondoy',stack_state_id:'14')
StackCity.create(name:'Tovar',stack_state_id:'14')
StackCity.create(name:'Tucani',stack_state_id:'14')
StackCity.create(name:'Zea',stack_state_id:'14')

#miranda

StackCity.create(name:'Araguita',stack_state_id:'15')
StackCity.create(name:'Carrizal',stack_state_id:'15')
StackCity.create(name:'Caucagua',stack_state_id:'15')
StackCity.create(name:'Chaguaramas Miranda',stack_state_id:'15')
StackCity.create(name:'Charallave',stack_state_id:'15')
StackCity.create(name:'Chirimena',stack_state_id:'15')
StackCity.create(name:'Chuspa',stack_state_id:'15')
StackCity.create(name:'Cúa',stack_state_id:'15')
StackCity.create(name:'Cupira',stack_state_id:'15')
StackCity.create(name:'Curiepe',stack_state_id:'15')
StackCity.create(name:'El Guapo',stack_state_id:'15')
StackCity.create(name:'El Jarillo',stack_state_id:'15')
StackCity.create(name:'Filas de Mariche',stack_state_id:'15')
StackCity.create(name:'Guarenas',stack_state_id:'15')
StackCity.create(name:'Guatire',stack_state_id:'15')
StackCity.create(name:'Higuerote',stack_state_id:'15')
StackCity.create(name:'Los Anaucos',stack_state_id:'15')
StackCity.create(name:'Los Teques',stack_state_id:'15')
StackCity.create(name:'Ocumare del Tuy',stack_state_id:'15')
StackCity.create(name:'Panaquire',stack_state_id:'15')
StackCity.create(name:'Paracotos',stack_state_id:'15')
StackCity.create(name:'Río Chico',stack_state_id:'15')
StackCity.create(name:'San Antonio de Los Altos',stack_state_id:'15')
StackCity.create(name:'San Diego de Los Altos',stack_state_id:'15')
StackCity.create(name:'San Fernando del Guapo',stack_state_id:'15')
StackCity.create(name:'San Francisco de Yare',stack_state_id:'15')
StackCity.create(name:'San José de Los Altos',stack_state_id:'15')
StackCity.create(name:'San José de Río Chico',stack_state_id:'15')
StackCity.create(name:'San Pedro de Los Altos',stack_state_id:'15')
StackCity.create(name:'Santa Lucía',stack_state_id:'15')
StackCity.create(name:'Santa Teresa',stack_state_id:'15')
StackCity.create(name:'Tacarigua de La Laguna',stack_state_id:'15')
StackCity.create(name:'Tacarigua de Mamporal',stack_state_id:'15')
StackCity.create(name:'Tácata',stack_state_id:'15')
StackCity.create(name:'Turumo',stack_state_id:'15')

#monagas

StackCity.create(name:'Aguasay',stack_state_id:'16')
StackCity.create(name:'Aragua de Maturín',stack_state_id:'16')
StackCity.create(name:'Barrancas del Orinoco',stack_state_id:'16')
StackCity.create(name:'Caicara de Maturín',stack_state_id:'16')
StackCity.create(name:'Caripe',stack_state_id:'16')
StackCity.create(name:'Caripito',stack_state_id:'16')
StackCity.create(name:'Chaguaramal',stack_state_id:'16')
StackCity.create(name:'Chaguaramas Monagas',stack_state_id:'16')
StackCity.create(name:'El Furrial',stack_state_id:'16')
StackCity.create(name:'El Tejero',stack_state_id:'16')
StackCity.create(name:'Jusepín',stack_state_id:'16')
StackCity.create(name:'La Toscana',stack_state_id:'16')
StackCity.create(name:'Maturín',stack_state_id:'16')
StackCity.create(name:'Miraflores',stack_state_id:'16')
StackCity.create(name:'Punta de Mata',stack_state_id:'16')
StackCity.create(name:'Quiriquire',stack_state_id:'16')
StackCity.create(name:'San Antonio de Maturín',stack_state_id:'16')
StackCity.create(name:'San Vicente Monagas',stack_state_id:'16')
StackCity.create(name:'Santa Bárbara',stack_state_id:'16')
StackCity.create(name:'Temblador',stack_state_id:'16')
StackCity.create(name:'Teresen',stack_state_id:'16')
StackCity.create(name:'Uracoa',stack_state_id:'16')

#nueva esparta

StackCity.create(name:'Altagracia',stack_state_id:'17')
StackCity.create(name:'Boca de Pozo',stack_state_id:'17')
StackCity.create(name:'Boca de Río',stack_state_id:'17')
StackCity.create(name:'El Espinal',stack_state_id:'17')
StackCity.create(name:'El Valle del Espíritu Santo',stack_state_id:'17')
StackCity.create(name:'El Yaque',stack_state_id:'17')
StackCity.create(name:'Juangriego',stack_state_id:'17')
StackCity.create(name:'La Asunción',stack_state_id:'17')
StackCity.create(name:'La Guardia',stack_state_id:'17')
StackCity.create(name:'Pampatar',stack_state_id:'17')
StackCity.create(name:'Porlamar',stack_state_id:'17')
StackCity.create(name:'Puerto Fermín',stack_state_id:'17')
StackCity.create(name:'Punta de Piedras',stack_state_id:'17')
StackCity.create(name:'San Francisco de Macanao',stack_state_id:'17')
StackCity.create(name:'San Juan Bautista',stack_state_id:'17')
StackCity.create(name:'San Pedro de Coche',stack_state_id:'17')
StackCity.create(name:'Santa Ana de Nueva Esparta',stack_state_id:'17')
StackCity.create(name:'Villa Rosa',stack_state_id:'17')

#portuguesa

StackCity.create(name:'Acarigua',stack_state_id:'18')
StackCity.create(name:'Agua Blanca',stack_state_id:'18')
StackCity.create(name:'Araure',stack_state_id:'18')
StackCity.create(name:'Biscucuy',stack_state_id:'18')
StackCity.create(name:'Boconoito',stack_state_id:'18')
StackCity.create(name:'Campo Elías',stack_state_id:'18')
StackCity.create(name:'Chabasquén',stack_state_id:'18')
StackCity.create(name:'Guanare',stack_state_id:'18')
StackCity.create(name:'Guanarito',stack_state_id:'18')
StackCity.create(name:'La Aparición',stack_state_id:'18')
StackCity.create(name:'La Misión',stack_state_id:'18')
StackCity.create(name:'Mesa de Cavacas',stack_state_id:'18')
StackCity.create(name:'Ospino',stack_state_id:'18')
StackCity.create(name:'Papelón',stack_state_id:'18')
StackCity.create(name:'Payara',stack_state_id:'18')
StackCity.create(name:'Pimpinela',stack_state_id:'18')
StackCity.create(name:'Píritu de Portuguesa',stack_state_id:'18')
StackCity.create(name:'San Rafael de Onoto',stack_state_id:'18')
StackCity.create(name:'Santa Rosalía',stack_state_id:'18')
StackCity.create(name:'Turén',stack_state_id:'18')

#sucre

StackCity.create(name:'Altos de Sucre',stack_state_id:'19')
StackCity.create(name:'Araya',stack_state_id:'19')
StackCity.create(name:'Cariaco',stack_state_id:'19')
StackCity.create(name:'Carúpano',stack_state_id:'19')
StackCity.create(name:'Casanay',stack_state_id:'19')
StackCity.create(name:'Cumaná',stack_state_id:'19')
StackCity.create(name:'Cumanacoa',stack_state_id:'19')
StackCity.create(name:'El Morro Puerto Santo',stack_state_id:'19')
StackCity.create(name:'El Pilar',stack_state_id:'19')
StackCity.create(name:'El Poblado',stack_state_id:'19')
StackCity.create(name:'Guaca',stack_state_id:'19')
StackCity.create(name:'Guiria',stack_state_id:'19')
StackCity.create(name:'Irapa',stack_state_id:'19')
StackCity.create(name:'Manicuare',stack_state_id:'19')
StackCity.create(name:'Mariguitar',stack_state_id:'19')
StackCity.create(name:'Río Caribe',stack_state_id:'19')
StackCity.create(name:'San Antonio del Golfo',stack_state_id:'19')
StackCity.create(name:'San José de Aerocuar',stack_state_id:'19')
StackCity.create(name:'San Vicente de Sucre',stack_state_id:'19')
StackCity.create(name:'Santa Fe de Sucre',stack_state_id:'19')
StackCity.create(name:'Tunapuy',stack_state_id:'19')
StackCity.create(name:'Yaguaraparo',stack_state_id:'19')
StackCity.create(name:'Yoco',stack_state_id:'19')

#tachira

StackCity.create(name:'Abejales',stack_state_id:'20')
StackCity.create(name:'Borota',stack_state_id:'20')
StackCity.create(name:'Bramon',stack_state_id:'20')
StackCity.create(name:'Capacho',stack_state_id:'20')
StackCity.create(name:'Colón',stack_state_id:'20')
StackCity.create(name:'Coloncito',stack_state_id:'20')
StackCity.create(name:'Cordero',stack_state_id:'20')
StackCity.create(name:'El Cobre',stack_state_id:'20')
StackCity.create(name:'El Pinal',stack_state_id:'20')
StackCity.create(name:'Independencia',stack_state_id:'20')
StackCity.create(name:'La Fría',stack_state_id:'20')
StackCity.create(name:'La Grita',stack_state_id:'20')
StackCity.create(name:'La Pedrera',stack_state_id:'20')
StackCity.create(name:'La Tendida',stack_state_id:'20')
StackCity.create(name:'Las Delicias',stack_state_id:'20')
StackCity.create(name:'Las Hernández',stack_state_id:'20')
StackCity.create(name:'Lobatera',stack_state_id:'20')
StackCity.create(name:'Michelena',stack_state_id:'20')
StackCity.create(name:'Palmira',stack_state_id:'20')
StackCity.create(name:'Pregonero',stack_state_id:'20')
StackCity.create(name:'Queniquea',stack_state_id:'20')
StackCity.create(name:'Rubio',stack_state_id:'20')
StackCity.create(name:'San Antonio del Tachira',stack_state_id:'20')
StackCity.create(name:'San Cristobal',stack_state_id:'20')
StackCity.create(name:'San José de Bolívar',stack_state_id:'20')
StackCity.create(name:'San Josecito',stack_state_id:'20')
StackCity.create(name:'San Pedro del Río',stack_state_id:'20')
StackCity.create(name:'Santa Ana Táchira',stack_state_id:'20')
StackCity.create(name:'Seboruco',stack_state_id:'20')
StackCity.create(name:'Táriba',stack_state_id:'20')
StackCity.create(name:'Umuquena',stack_state_id:'20')

#trujillo

StackCity.create(name:'Batatal',stack_state_id:'21')
StackCity.create(name:'Betijoque',stack_state_id:'21')
StackCity.create(name:'Boconó',stack_state_id:'21')
StackCity.create(name:'Carache',stack_state_id:'21')
StackCity.create(name:'Chejende',stack_state_id:'21')
StackCity.create(name:'Cuicas',stack_state_id:'21')
StackCity.create(name:'El Dividive',stack_state_id:'21')
StackCity.create(name:'El Jaguito',stack_state_id:'21')
StackCity.create(name:'Escuque',stack_state_id:'21')
StackCity.create(name:'Isnotú',stack_state_id:'21')
StackCity.create(name:'Jajó',stack_state_id:'21')
StackCity.create(name:'La Ceiba',stack_state_id:'21')
StackCity.create(name:'La Concepción de Trujllo',stack_state_id:'21')
StackCity.create(name:'La Mesa de Esnujaque',stack_state_id:'21')
StackCity.create(name:'La Puerta',stack_state_id:'21')
StackCity.create(name:'La Quebrada',stack_state_id:'21')
StackCity.create(name:'Mendoza Fría',stack_state_id:'21')
StackCity.create(name:'Meseta de Chimpire',stack_state_id:'21')
StackCity.create(name:'Monay',stack_state_id:'21')
StackCity.create(name:'Motatán',stack_state_id:'21')
StackCity.create(name:'Pampán',stack_state_id:'21')
StackCity.create(name:'Pampanito',stack_state_id:'21')
StackCity.create(name:'Sabana de Mendoza',stack_state_id:'21')
StackCity.create(name:'San Lázaro',stack_state_id:'21')
StackCity.create(name:'Santa Ana de Trujillo',stack_state_id:'21')
StackCity.create(name:'Tostós',stack_state_id:'21')
StackCity.create(name:'Trujillo',stack_state_id:'21')
StackCity.create(name:'Valera',stack_state_id:'21')

#vargas

StackCity.create(name:'Carayaca',stack_state_id:'22')
StackCity.create(name:'Litoral',stack_state_id:'22')

#yaracuy

StackCity.create(name:'Aroa',stack_state_id:'23')
StackCity.create(name:'Boraure',stack_state_id:'23')
StackCity.create(name:'Campo Elías de Yaracuy',stack_state_id:'23')
StackCity.create(name:'Chivacoa',stack_state_id:'23')
StackCity.create(name:'Cocorote',stack_state_id:'23')
StackCity.create(name:'Farriar',stack_state_id:'23')
StackCity.create(name:'Guama',stack_state_id:'23')
StackCity.create(name:'Marín',stack_state_id:'23')
StackCity.create(name:'Nirgua',stack_state_id:'23')
StackCity.create(name:'Sabana de Parra',stack_state_id:'23')
StackCity.create(name:'Salom',stack_state_id:'23')
StackCity.create(name:'San Felipe',stack_state_id:'23')
StackCity.create(name:'San Pablo de Yaracuy',stack_state_id:'23')
StackCity.create(name:'Urachiche',stack_state_id:'23')
StackCity.create(name:'Yaritagua',stack_state_id:'23')
StackCity.create(name:'Yumare',stack_state_id:'23')

#zulia

StackCity.create(name:'Bachaquero',stack_state_id:'24')
StackCity.create(name:'Bobures',stack_state_id:'24')
StackCity.create(name:'Cabimas',stack_state_id:'24')
StackCity.create(name:'Campo Concepción',stack_state_id:'24')
StackCity.create(name:'Campo Mara',stack_state_id:'24')
StackCity.create(name:'Campo Rojo',stack_state_id:'24')
StackCity.create(name:'Carrasquero',stack_state_id:'24')
StackCity.create(name:'Casigua',stack_state_id:'24')
StackCity.create(name:'Chiquinquirá',stack_state_id:'24')
StackCity.create(name:'Ciudad Ojeda',stack_state_id:'24')
StackCity.create(name:'El Batey',stack_state_id:'24')
StackCity.create(name:'El Carmelo',stack_state_id:'24')
StackCity.create(name:'El Chivo',stack_state_id:'24')
StackCity.create(name:'El Guayabo',stack_state_id:'24')
StackCity.create(name:'El Mene',stack_state_id:'24')
StackCity.create(name:'El Venado',stack_state_id:'24')
StackCity.create(name:'Encontrados',stack_state_id:'24')
StackCity.create(name:'Gibraltar',stack_state_id:'24')
StackCity.create(name:'Isla de Toas',stack_state_id:'24')
StackCity.create(name:'La Concepción',stack_state_id:'24')
StackCity.create(name:'La Paz',stack_state_id:'24')
StackCity.create(name:'La Sierrita',stack_state_id:'24')
StackCity.create(name:'Lagunillas',stack_state_id:'24')
StackCity.create(name:'Las Piedras',stack_state_id:'24')
StackCity.create(name:'Los Cortijos',stack_state_id:'24')
StackCity.create(name:'Machiques',stack_state_id:'24')
StackCity.create(name:'Maracaibo',stack_state_id:'24')
StackCity.create(name:'Mene Grande',stack_state_id:'24')
StackCity.create(name:'Palmarejo',stack_state_id:'24')
StackCity.create(name:'Paraguaipoa',stack_state_id:'24')
StackCity.create(name:'Potrerito',stack_state_id:'24')
StackCity.create(name:'Pueblo Nuevo',stack_state_id:'24')
StackCity.create(name:'Puertos de Altagracia',stack_state_id:'24')
StackCity.create(name:'Punta Gorda',stack_state_id:'24')
StackCity.create(name:'Sabaneta de Palma',stack_state_id:'24')
StackCity.create(name:'San Francisco',stack_state_id:'24')
StackCity.create(name:'San José de Perijá',stack_state_id:'24')
StackCity.create(name:'San Rafael del Moján',stack_state_id:'24')
StackCity.create(name:'San Timoteo',stack_state_id:'24')
StackCity.create(name:'Santa Bárbara del Zulia',stack_state_id:'24')
StackCity.create(name:'Santa Cruz de Mara',stack_state_id:'24')
StackCity.create(name:'Santa Cruz del Zulia',stack_state_id:'24')
StackCity.create(name:'Santa Rita',stack_state_id:'24')
StackCity.create(name:'Sinamaica',stack_state_id:'24')
StackCity.create(name:'Tamare',stack_state_id:'24')
StackCity.create(name:'Tía Juana',stack_state_id:'24')
StackCity.create(name:'Villa Rosario',stack_state_id:'24')

puts 'admin@keppler.com has been created'

Customize.create(file: "", installed: true)
puts 'Keppler Template has been created'
# Create setting deafult
setting = Setting.new(
  name: 'Keppler Admin', description: 'Welcome to Keppler Admin',
  smtp_setting_attributes: {
    address: 'test', port: '25', domain_name: 'keppler.com',
    email: 'info@keppler.com', password: '12345678'
  },
  google_analytics_setting_attributes: {
    ga_account_id: '60688852',
    ga_tracking_id: 'UA-60688852-1',
    ga_status: true
  }
)
setting.social_account = SocialAccount.new
setting.appearance = Appearance.new(theme_name: 'keppler')
setting.save
puts 'Setting default has been created'

KepplerContactUs::MessageSetting.create(
mailer_to:"gagg1707@gmail.com",
mailer_from:"gagg1707@gmail.com"
)
puts 'Mailer From & Mailer To has been created'